/// Flutter icons multipurpose_toilet
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  multipurpose_toilet
///      fonts:
///       - asset: fonts/multipurpose_toilet.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';


// ダウンロードした画像をiconとして使うためのコード
class multipurpose_toilet {
  multipurpose_toilet._();

  static const _kFontFam = 'multipurpose_toilet';
  static const String? _kFontPkg = null;

  static const IconData wheelchair = IconData(0xf193, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
